FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./CDF-events-PoC.png usr/share/nginx/html/CDF-events-PoC.png
COPY ./techday-cdevents-visualisation-functional.png usr/share/nginx/html/techday-cdevents-visualisation-functional.png
