FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./CDF-events-PoC.png usr/share/nginx/html/CDF-events-PoC.png
COPY ./CDF-events-spinnaker-PoC.png usr/share/nginx/html/CDF-events-spinnaker-PoC.png
