apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-echo-poc-deployment
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-echo-poc
  template:
    metadata:
      labels:
        app: spinnaker-echo-poc
    spec:
      containers:
        - image: 'localhost:5000/cdevents/spinnaker-echo-poc'
          name: spinnaker-echo-poc
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: spin-echo
  namespace: spinnaker
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: spinnaker-echo-poc
  type: ClusterIP
