on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
name: Send CDEvent
jobs:
  sendCDEvent:
    name: Send CDEvent
    runs-on: ubuntu-latest
    steps:
    - name: send CDEvent
      uses: rjalander/github-action@main
      with:
        source: 'https://github.com/rjalander/sig-events'
        subject_id: 'main'
        subject_pipeline_name: 'myPipeline'
        subject_url: 'https://example.com/myPipeline'
        version: 0.0.1
